import 'package:expense_tracker/Models/ExpenseCategory.dart';
import 'package:expense_tracker/Models/Transaction.dart';

List<Transaction> dummyData = [
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
  Transaction(
    category: ExpenseCategory.HEALTH,
    title: "Fracture",
    amount: 200.0,
    type: ExpenseType.INCOME,
    dateTime: DateTime.now(),
  ),
];
